name: Labels
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  labeler:
    name: Labels
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          skip-delete: true